version: '3.8'

services:
  dev:
    container_name: task
    image: task:1.0.0
    env_file:
      - .env
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: yarn start:docker
    depends_on:
      - taskdb
    networks:
      - default
      - tasksnetwork
    volumes:
      - .:/usr/src/task
    restart: unless-stopped
  prod:
    container_name: task-prod
    image: task:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: yarn start:prod
    depends_on:
      - taskdb
    networks:
      - default
      - tasksnetwork
    volumes:
      - .:/usr/src/task
    restart: unless-stopped
  taskdb:
    image : mongo:latest
    env_file:
      - .env
    container_name: $DB_HOST
    volumes:
      - mongodata:/data/db
    command: mongod --port $DB_PORT
    ports:
      - $DB_PORT:$DB_PORT
    networks:
      - tasksnetwork
    restart: always

networks:
    tasksnetwork:
      driver: bridge
    default:
      external: true
      name: application

volumes:
  mongodata: