version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqvolum:/broker
    networks:
      - default

networks:
  default:
    driver: bridge
    name: application

volumes:
  rabbitmqvolum: